/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../EntityId';

import { ReferenceSearchInput } from './ReferenceSearchInput';

// <keep-imports>
// </keep-imports>

@InputType()
export class PostSearchInput {
  @Field(() => EntityIdScalar, { nullable: true })
  public id?: EntityId;

  @Field(() => String, { nullable: true })
  public content?: string | null;

  @Field(() => String, { nullable: true })
  public title?: string | null;

  @Field(() => ReferenceSearchInput, { nullable: true })
  public author?: ReferenceSearchInput | null;

  // <keep-methods>
  // </keep-methods>
}
