/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../EntityId';
import { UserRole } from '../enums/UserRole';
import { SortOrderEnum } from '../SortOrderEnum';

// <keep-imports>
// </keep-imports>

@InputType()
export class UserSearchOrderInput {
  @Field(() => EntityIdScalar, { nullable: true })
  public id?: EntityId;

  @Field(() => String, { nullable: true })
  public email?: string | null;

  @Field(() => String, { nullable: true })
  public password?: string | null;

  @Field(() => String, { nullable: true })
  public firstName?: string | null;

  @Field(() => String, { nullable: true })
  public lastName?: string | null;

  @Field(() => String, { nullable: true })
  public fullName?: string | null;

  @Field(() => SortOrderEnum, { nullable: true })
  public profileImage?: SortOrderEnum | null;

  // <keep-methods>
  // </keep-methods>
}
