/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, ObjectType } from 'type-graphql';
import { Column, JoinColumn, Entity, OneToOne, ManyToOne, OneToMany, PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn } from 'typeorm';

import { Post } from '../../post/models/Post';
import { File } from '../../file/models/File';
import { UserRole } from '../enums/UserRole';
import * as auth from '../../authorization/auth-checkers';
import { UserCreateInput } from '../inputs/UserCreateInput';
import { UserEditInput } from '../inputs/UserEditInput';
import { UserNestedInput } from '../inputs/UserNestedInput';
import { IRequestContext } from '../../shared/IRequestContext';
import { IAuthorizable } from '../../authorization/IAuthorizable';
import { EntityId, EntityIdScalar } from '../../shared/EntityId';
import { UserAuth } from '../auth/UserAuth';
import { getInputOperationType } from '../../shared/get-input-operation-type';
import { noChange } from '../../shared/no-change';
import { asPromise } from '../../shared/as-promise';

import { updateProfileImageRelation } from './update-operations/user-update-operations';

// <keep-imports>
import {hashPassword, verifyPassword} from '../../authentication/crypto';
// </keep-imports>

// <keep-decorators>
// </keep-decorators>
@Entity()
@ObjectType()
export class User implements IAuthorizable {
  @Field(() => EntityIdScalar)
  @PrimaryGeneratedColumn()
  id: EntityId;

  public authorizationChecker = new UserAuth(this);

  @Field(() => String, )
  @Column({"type":"varchar",
    // <custom-column-args>
    unique: true,
    // </custom-column-args>
  })
  public email: string;

  
  @Column({"type":"varchar",
    // <custom-column-args>
    // </custom-column-args>
  })
  public passwordHash: string;

  @Field(() => String, )
  @Column({
    // <custom-column-args>
    // </custom-column-args>
  })
  public firstName: string;

  @Field(() => String, )
  @Column({
    // <custom-column-args>
    // </custom-column-args>
  })
  public lastName: string;

  
  @Column({"enum":UserRole,
    // <custom-column-args>
    // </custom-column-args>
  })
  public role: UserRole;

  @OneToMany(() => Post, (post) => post.author)
  @Field(() => [Post])
  public posts: Promise<Array<Post>>;

  @OneToOne(() => File, (file) => file.user)
  @Field(() => File , {"nullable":true})
  public profileImage: Promise<File | undefined | null>;

  @CreateDateColumn()
  @Field()
  createdAt: Date;

  @UpdateDateColumn()
  @Field()
  updatedAt: Date;

  public async update(input: UserCreateInput | UserEditInput | UserNestedInput, context: IRequestContext) {
    const { profileImage, ...data } = input;
    if (noChange(input)) {
      return this;
    }
    if (getInputOperationType(this, input) === 'update') {
      await auth.assertCanUpdate(this, context);
    }
    Object.assign(this, data);

    await updateProfileImageRelation(this, profileImage, context);

    context.modelsToSave.push(this);

    // <keep-update-code>
    if (this.role === undefined) {
      this.role = UserRole.USER;
    }
    if (this.passwordHash === undefined && input.password) {
      this.passwordHash = await hashPassword(input.password);
    }
    // </keep-update-code>
    await auth.assertCanPersist(this, context);

    return this;
  }

  // <keep-methods>
  public async passwordMatches(password: string) {
    return verifyPassword(password, this.passwordHash);
  }
  // </keep-methods>
}
