/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
// tslint:disable max-line-length no-duplicate-imports
import { Field, ID, ObjectType } from 'type-graphql';
import { Column, CreateDateColumn, Entity, JoinColumn, ManyToOne, OneToMany, OneToOne, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';

import { File } from '../../File/models/File';
import { Post } from '../../Post/models/Post';
import { asPromise } from '../../shared/as-promise';
import { EntityId, EntityIdScalar } from '../../shared/EntityId';
import { getInputOperationType } from '../../shared/get-input-operation-type';
import { IRequestContext } from '../../shared/IRequestContext';
import { noChange } from '../../shared/no-change';
import * as auth from '../../authorization/auth-checkers';
import { IAuthorizable } from '../../authorization/IAuthorizable';
import { UserAuth } from '../auth/UserAuth';
import { UserRole } from '../enums/UserRole';
import { UserCreateInput } from '../inputs/UserCreateInput';
import { UserEditInput } from '../inputs/UserEditInput';
import { UserNestedInput } from '../inputs/UserNestedInput';
import { updateProfileImageRelation } from './update-operations/user-update-operations';

// <keep-imports>
import { verifyPassword } from '../../Authentication/crypto';
// </keep-imports>

// <keep-decorators>
// </keep-decorators>
@Entity()
@ObjectType()
export class User implements IAuthorizable {
  @Field(() => EntityIdScalar)
  @PrimaryGeneratedColumn()
  public id: EntityId;

  public authorizationChecker = new UserAuth(this);

  @Field(() => String, { nullable: true })
  @Column({nullable: true, type: 'varchar',
    // <custom-column-args>
    // </custom-column-args>
  })
  public email?: string | null;

  @Column({nullable: true, type: 'varchar',
    // <custom-column-args>
    // </custom-column-args>
  })
  public passwordHash?: string | null;

  @Field(() => String)
  @Column({
    // <custom-column-args>
    // </custom-column-args>
  })
  public firstName: string;

  @Field(() => String)
  @Column({
    // <custom-column-args>
    // </custom-column-args>
  })
  public lastName: string;

  @Column({enum: UserRole,
    // <custom-column-args>
    // </custom-column-args>
  })
  public role: UserRole;

  @OneToMany(() => Post, (post) => post.author)
  @Field(() => [Post])
  public posts: Promise<Array<Post>>;

  @OneToOne(() => File, (file) => file.user)
  @Field(() => File , { nullable: true })
  public profileImage: Promise<File | undefined | null>;

  @CreateDateColumn()
  @Field()
  public createdAt: Date;

  @UpdateDateColumn()
  @Field()
  public updatedAt: Date;

  public async update(input: UserCreateInput | UserEditInput | UserNestedInput, context: IRequestContext) {
    const { profileImage, ...data } = input;
    if (noChange(input)) {
      return this;
    }
    if (getInputOperationType(this, input) === 'update') {
      await auth.assertCanUpdate(this, context);
    }
    Object.assign(this, data);

    await updateProfileImageRelation(this, profileImage, context);

    context.modelsToSave.push(this);

    // <keep-update-code>
    // </keep-update-code>
    await auth.assertCanPersist(this, context);

    return this;
  }

  // <keep-methods>
  public async passwordMatches(password: string) {
    return verifyPassword(password, this.passwordHash);
  }
  // </keep-methods>
}
