version: '3'
services:
 technobabble-template:
   container_name: technobabble-template
   image: postgres:10-alpine
   restart: always
   ports:
   - "5401:5432"
   environment:
     POSTGRES_USER: user
     POSTGRES_PASSWORD: 1234
     POSTGRES_DB: technobabble-template
