version: '3'
services:
 talentengien:
   container_name: talentengien
   image: postgres:10-alpine
   restart: always
   ports:
   - "32863:5432"
   environment:
     POSTGRES_USER: user
     POSTGRES_PASSWORD: 1234
     POSTGRES_DB: talentengien
