/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
// tslint:disable max-line-length no-duplicate-imports
import { Field, ID, ObjectType } from 'type-graphql';
import { Column, CreateDateColumn, Entity, JoinColumn, ManyToOne, OneToMany, OneToOne, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';

import { Talent } from '../../Talent/models/Talent';

import { asPromise } from '../../../utils/as-promise';
import * as auth from '../../../utils/auth/auth-checkers';
import { IAuthorizable } from '../../../utils/auth/IAuthorizable';
import { getInputOperationType } from '../../../utils/get-input-operation-type';
import { noChange } from '../../../utils/no-change';
import { EntityId, EntityIdScalar } from '../../EntityId';
import { IRequestContext } from '../../IRequestContext';
import { AgentAuth } from '../auth/AgentAuth';
import { AgentCreateInput } from '../inputs/AgentCreateInput';
import { AgentEditInput } from '../inputs/AgentEditInput';
import { AgentNestedInput } from '../inputs/AgentNestedInput';
import {  } from './update-operations/agent-update-operations';

// <keep-imports>
// </keep-imports>

// <keep-decorators>
// </keep-decorators>
@Entity()
@ObjectType()
export class Agent implements IAuthorizable {
  @Field(() => EntityIdScalar)
  @PrimaryGeneratedColumn()
  public id: EntityId;

  public authorizationChecker = new AgentAuth(this);

  @Field(() => String)
  @Column({
    // <custom-column-args>
    // </custom-column-args>
  })
  public firstName: string;

  @Field(() => String)
  @Column({
    // <custom-column-args>
    // </custom-column-args>
  })
  public lastName: string;

  @OneToMany(() => Talent, (talent) => talent.agent)
  @Field(() => [Talent])
  public talents: Promise<Array<Talent>>;

  @CreateDateColumn()
  @Field()
  public createdAt: Date;

  @UpdateDateColumn()
  @Field()
  public updatedAt: Date;

  public async update(input: AgentCreateInput | AgentEditInput | AgentNestedInput, context: IRequestContext) {
    const data = input;
    if (noChange(input)) {
      return this;
    }
    if (getInputOperationType(this, input) === 'update') {
      await auth.assertCanUpdate(this, context);
    }
    Object.assign(this, data);

    context.modelsToSave.push(this);

    // <keep-update-code>
    // </keep-update-code>
    await auth.assertCanPersist(this, context);

    return this;
  }

  // <keep-methods>
  // </keep-methods>
}
