/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../../EntityId';
import { FileNestedInput } from '../../Profileimage/inputs/FileNestedInput';
import { UserRole } from '../enums/UserRole';

// <keep-imports>
// </keep-imports>

@InputType()
export class UserCreateInput {
  @Field(() => String, { nullable: true })
  public email?: string | null;

  @Field(() => String)
  public password: string;

  @Field(() => String)
  public firstName: string;

  @Field(() => String)
  public lastName: string;

  @Field(() => FileNestedInput, { nullable: true })
  public profileImage?: FileNestedInput | null;

  // <keep-methods>
  // </keep-methods>
}
