/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../../shared/EntityId';
import { UserRole } from '../enums/UserRole';
import { SortOrderEnum } from '../../shared/SortOrderEnum'

// <keep-imports>
// </keep-imports>

@InputType()
export class UserSearchOrderInput {
  @Field(() => SortOrderEnum, {"nullable":true})
  public id?: SortOrderEnum;

  @Field(() => SortOrderEnum, {"nullable":true})
  public email?: SortOrderEnum | null;

  @Field(() => SortOrderEnum, {"nullable":true})
  public password?: SortOrderEnum | null;

  @Field(() => SortOrderEnum, {"nullable":true})
  public firstName?: SortOrderEnum | null;

  @Field(() => SortOrderEnum, {"nullable":true})
  public lastName?: SortOrderEnum | null;

  @Field(() => SortOrderEnum, {"nullable":true})
  public profileImage?: SortOrderEnum | null;

  @Field(() => SortOrderEnum, {"nullable":true})
  public createdAt?: SortOrderEnum | null;

  @Field(() => SortOrderEnum, {"nullable":true})
  public updatedAt?: SortOrderEnum | null;

  // <keep-methods>
  // </keep-methods>
}
