/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../../shared/EntityId';
import { UserRole } from '../enums/UserRole';
import { FileNestedInput } from '../../file/inputs/FileNestedInput'

// <keep-imports>
// </keep-imports>

@InputType()
export class UserCreateInput {
  @Field(() => String, )
  public email: string;

  @Field(() => String, )
  public password: string;

  @Field(() => String, )
  public firstName: string;

  @Field(() => String, )
  public lastName: string;

  @Field(() => FileNestedInput, {"nullable":true})
  public profileImage?: FileNestedInput | null;

  // <keep-methods>
  // </keep-methods>
}
