/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../../EntityId';

import { AgentNestedInput } from '../../Agent/inputs/AgentNestedInput';

// <keep-imports>
// </keep-imports>

@InputType()
export class TalentCreateInput {
  @Field(() => String)
  public firstName: string;

  @Field(() => String)
  public lastName: string;

  @Field(() => AgentNestedInput, { nullable: true })
  public agent?: AgentNestedInput | null;

  // <keep-methods>
  // </keep-methods>
}
