/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
// tslint:disable max-line-length
import * as cleanDeep from 'clean-deep';
import { Arg, Args, Ctx, FieldResolver, ID, Info, Int, Mutation, Query, Resolver, Root } from 'type-graphql';

import { addEagerFlags } from '../../../utils/add-eager-flags';
import * as auth from '../../../utils/auth/auth-checkers';
import { getFindOptions } from '../../../utils/get-find-options';
import { resolveGetters } from '../../../utils/resolve-getters';
import { EntityId, EntityIdScalar } from '../../EntityId';
import { IRequestContext } from '../../IRequestContext';
import { PaginatedResponse } from '../../PaginationResponse';
import { AgentCreateInput } from '../inputs/AgentCreateInput';
import { AgentEditInput } from '../inputs/AgentEditInput';
import { AgentSearchInput } from '../inputs/AgentSearchInput';
import { AgentSearchOrderInput } from '../inputs/AgentSearchOrderInput';
import { Agent } from '../models/Agent';

// <keep-imports>
// </keep-imports>

const PaginatedAgentResponse = PaginatedResponse(Agent);

@Resolver(Agent)
export class AgentCrudResolver {
  @Query(() => Agent)
  public async agent(@Arg('id', () => EntityIdScalar) id: number, @Info() info, @Ctx() ctx: IRequestContext) {
    return addEagerFlags(await ctx.em.findOneOrFail(Agent, id, getFindOptions(Agent, info)));
  }

  @Query(() => PaginatedAgentResponse)
  public async searchAgents(
    @Arg('search', () => AgentSearchInput, { nullable: true }) search: AgentSearchInput | null = null,
    @Arg('skip', () => Int, { nullable: true }) skip: number = 0,
    @Arg('take', () => Int, { nullable: true }) take: number = 25,
    @Arg('order', () => [AgentSearchOrderInput], { nullable: true }) order: Array<AgentSearchOrderInput> = [],
    @Info() info,
    @Ctx() ctx: IRequestContext,
  ) {
    const defaultFindOptions = getFindOptions(Agent, info, { transformQueryPath: x => x.replace(/^items./, '') });

    const [items, total] = addEagerFlags(await ctx.em.findAndCount(Agent, cleanDeep({
      ...defaultFindOptions,
      skip,
      take,
      where: resolveGetters(search),
      order: Object.assign({}, ...order),
    })));

    return {
      items,
      total,
      hasMore: skip + take < total,
    };
  }

  @Query(() => [Agent])
  public async agents(@Info() info, @Ctx() ctx: IRequestContext) {
    return addEagerFlags(await ctx.em.find(Agent, getFindOptions(Agent, info)));
  }

  @Mutation(() => Agent)
  public async createAgent(@Arg('input') input: AgentCreateInput, @Ctx() ctx: IRequestContext): Promise<Agent> {
    const model = new Agent();
    await model.update(input, ctx);

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Agent)
  public async updateAgent(@Arg('input') input: AgentEditInput, @Ctx() ctx: IRequestContext) {
    const model = await ctx.em.findOneOrFail(Agent, input.id);
    await model.update(input, ctx);

    // <keep-update-code>
    // </keep-update-code>

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Boolean)
  public async deleteAgents(@Arg('ids', () => [ID]) ids: Array<EntityId>, @Ctx() ctx: IRequestContext): Promise<boolean> {
    const entities = await ctx.em.findByIds(Agent, ids);
    await auth.assertCanDelete(entities, ctx);
    await ctx.em.remove(entities);

    return true;
  }

  // <keep-methods>
  // </keep-methods>
}
