/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { ReferenceSearchInput } from '../../inputs/ReferenceSearchInput';
import { EntityId, EntityIdScalar } from '../../shared/EntityId';
import { UserRole } from '../enums/UserRole';

// <keep-imports>
// </keep-imports>

@InputType()
export class UserSearchInput {
  @Field(() => EntityIdScalar, { nullable: true })
  public id?: EntityId;

  @Field(() => String, { nullable: true })
  public email?: string | null;

  @Field(() => String, { nullable: true })
  public password?: string | null;

  @Field(() => String, { nullable: true })
  public firstName?: string | null;

  @Field(() => String, { nullable: true })
  public lastName?: string | null;

  @Field(() => ReferenceSearchInput, { nullable: true })
  public profileImage?: ReferenceSearchInput | null;

  // <keep-methods>
  // </keep-methods>
}
