/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../../EntityId';

import { PostNestedInput } from '../../Post/inputs/PostNestedInput';
import { UserNestedInput } from '../../User/inputs/UserNestedInput';

// <keep-imports>
// </keep-imports>

@InputType()
export class FileCreateInput {
  @Field(() => String)
  public contentBase64: string;

  @Field(() => PostNestedInput, { nullable: true })
  public post?: PostNestedInput | null;

  @Field(() => UserNestedInput, { nullable: true })
  public user?: UserNestedInput | null;

  // <keep-methods>
  // </keep-methods>
}
