/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
// tslint:disable max-line-length no-duplicate-imports
import { Field, ID, ObjectType } from 'type-graphql';
import { Column, CreateDateColumn, Entity, JoinColumn, ManyToOne, OneToMany, OneToOne, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';

import { Agent } from './Agent';

import { asPromise } from '../../utils/as-promise';
import * as auth from '../../utils/auth/auth-checkers';
import { IAuthorizable } from '../../utils/auth/IAuthorizable';
import { getInputOperationType } from '../../utils/get-input-operation-type';
import { noChange } from '../../utils/no-change';
import { TalentAuth } from '../auth/TalentAuth';
import { EntityId, EntityIdScalar } from '../EntityId';
import { TalentCreateInput } from '../inputs/TalentCreateInput';
import { TalentEditInput } from '../inputs/TalentEditInput';
import { TalentNestedInput } from '../inputs/TalentNestedInput';
import { IRequestContext } from '../IRequestContext';
import { updateAgentRelation } from './update-operations/talent-update-operations';

// <keep-imports>
// </keep-imports>

// <keep-decorators>
// </keep-decorators>
@Entity()
@ObjectType()
export class Talent implements IAuthorizable {
  @Field(() => EntityIdScalar)
  @PrimaryGeneratedColumn()
  public id: EntityId;

  public authorizationChecker = new TalentAuth(this);

  @Field(() => String)
  @Column({
    // <custom-column-args>
    // </custom-column-args>
  })
  public firstName: string;

  @Field(() => String)
  @Column({
    // <custom-column-args>
    // </custom-column-args>
  })
  public lastName: string;

  @ManyToOne(() => Agent, (agent) => agent.talents , { nullable: true, onDelete: 'SET NULL' })
  @Field(() => Agent , { nullable: true })
  public agent: Promise<Agent | undefined | null>;

  @CreateDateColumn()
  @Field()
  public createdAt: Date;

  @UpdateDateColumn()
  @Field()
  public updatedAt: Date;

  public async update(input: TalentCreateInput | TalentEditInput | TalentNestedInput, context: IRequestContext) {
    const { agent, ...data } = input;
    if (noChange(input)) {
      return this;
    }
    if (getInputOperationType(this, input) === 'update') {
      await auth.assertCanUpdate(this, context);
    }
    Object.assign(this, data);

    await updateAgentRelation(this, agent, context);

    context.modelsToSave.push(this);

    // <keep-update-code>
    // </keep-update-code>
    await auth.assertCanPersist(this, context);

    return this;
  }

  // <keep-methods>
  // </keep-methods>
}
