/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
// tslint:disable max-line-length no-duplicate-imports
import { Field, ID, ObjectType } from 'type-graphql';
import { Column, CreateDateColumn, Entity, JoinColumn, ManyToOne, OneToMany, OneToOne, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';

import * as auth from '../../utils/auth/auth-checkers';
import { IAuthorizable } from '../../utils/auth/IAuthorizable';
import { getInputOperationType } from '../../utils/get-input-operation-type';
import { UserAuth } from '../auth/UserAuth';
import { EntityId, EntityIdScalar } from '../EntityId';
import { UserRole } from '../enums/UserRole';
import { UserCreateInput } from '../inputs/UserCreateInput';
import { UserEditInput } from '../inputs/UserEditInput';
import { UserNestedInput } from '../inputs/UserNestedInput';
import { IRequestContext } from '../IRequestContext';
import { File } from './File';
import { Post } from './Post';
import { updateProfileImageRelation } from './update-operations/user-update-operations';

// <keep-imports>
import { hashPassword, verifyPassword } from '../../utils/crypto';
// </keep-imports>

// <keep-decorators>
// </keep-decorators>
@Entity()
@ObjectType()
export class User implements IAuthorizable {
  @Field((type) => EntityIdScalar)
  @PrimaryGeneratedColumn()
  public id: EntityId;

  public authorizationChecker = new UserAuth(this);

  @Field(() => String, { nullable: true })
  @Column({nullable: true, type: 'varchar',
    // <custom-column-args>
    // </custom-column-args>
  })
  public email?: string | null;

  @Column({nullable: true, type: 'varchar',
    // <custom-column-args>
    // </custom-column-args>
  })
  public passwordHash?: string | null;

  @Field(() => String)
  @Column({
    // <custom-column-args>
    // </custom-column-args>
  })
  public firstName: string;

  @Field(() => String)
  @Column({
    // <custom-column-args>
    // </custom-column-args>
  })
  public lastName: string;

  @Field(() => String, { nullable: true })
  @Column({nullable: true, type: 'varchar',
    // <custom-column-args>
    // </custom-column-args>
  })
  public fullName?: string | null;

  @Column({enum: UserRole,
    // <custom-column-args>
    // </custom-column-args>
  })
  public role: UserRole;

  @Column({nullable: true, type: 'varchar',
    // <custom-column-args>
    // </custom-column-args>
  })
  public accountVerificationCode?: string | null;

  @Column({nullable: true, type: 'varchar',
    // <custom-column-args>
    // </custom-column-args>
  })
  public forgotPasswordCode?: string | null;

  @Column({nullable: true, type: 'varchar',
    // <custom-column-args>
    // </custom-column-args>
  })
  public googleUserId?: string | null;

  @Column({nullable: true, type: 'varchar',
    // <custom-column-args>
    // </custom-column-args>
  })
  public googleToken?: string | null;

  @Column({nullable: true, type: 'varchar',
    // <custom-column-args>
    // </custom-column-args>
  })
  public facebookUserId?: string | null;

  @Column({nullable: true, type: 'varchar',
    // <custom-column-args>
    // </custom-column-args>
  })
  public facebookAccessToken?: string | null;

  @OneToMany((type) => Post, (post) => post.author)
  @Field((returns) => [Post])
  public posts: Promise<Array<Post>>;

  @OneToOne((type) => File, (file) => file.user)
  @Field((returns) => File , { nullable: true })
  public profileImage: Promise<File | undefined | null>;

  @CreateDateColumn()
  @Field()
  public createdAt: Date;

  @UpdateDateColumn()
  @Field()
  public updatedAt: Date;

  public async update(input: UserCreateInput | UserEditInput | UserNestedInput, context: IRequestContext) {
    const { profileImage, ...data } = input;
    if (getInputOperationType(this, input) === 'update') {
      await auth.assertCanUpdate(this, context);
    }
    Object.assign(this, data);

    await updateProfileImageRelation(this, profileImage, context);

    context.modelsToSave.push(this);

    // <keep-update-code>
    const { password } = input;
    this.passwordHash = password && await hashPassword(password);

    if (this.role === undefined) {
      this.role = UserRole.USER;
    }
    // </keep-update-code>
    await auth.assertCanPersist(this, context);

    return this;
  }

  // <keep-methods>
  public async passwordMatches(password: string) {
    return verifyPassword(password, this.passwordHash);
  }
  // </keep-methods>
}
