/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
// tslint:disable max-line-length
import * as cleanDeep from 'clean-deep';
import { Arg, Args, Ctx, FieldResolver, ID, Info, Int, Mutation, Query, Resolver, Root } from 'type-graphql';

import { addEagerFlags } from '../../../utils/add-eager-flags';
import * as auth from '../../../utils/auth/auth-checkers';
import { getFindOptions } from '../../../utils/get-find-options';
import { resolveGetters } from '../../../utils/resolve-getters';
import { EntityId, EntityIdScalar } from '../../EntityId';
import { IRequestContext } from '../../IRequestContext';
import { PaginatedResponse } from '../../PaginationResponse';
import { TalentCreateInput } from '../inputs/TalentCreateInput';
import { TalentEditInput } from '../inputs/TalentEditInput';
import { TalentSearchInput } from '../inputs/TalentSearchInput';
import { TalentSearchOrderInput } from '../inputs/TalentSearchOrderInput';
import { Talent } from '../models/Talent';

// <keep-imports>
// </keep-imports>

const PaginatedTalentResponse = PaginatedResponse(Talent);

@Resolver(Talent)
export class TalentCrudResolver {
  @Query(() => Talent)
  public async talent(@Arg('id', () => EntityIdScalar) id: number, @Info() info, @Ctx() ctx: IRequestContext) {
    return addEagerFlags(await ctx.em.findOneOrFail(Talent, id, getFindOptions(Talent, info)));
  }

  @Query(() => PaginatedTalentResponse)
  public async searchTalents(
    @Arg('search', () => TalentSearchInput, { nullable: true }) search: TalentSearchInput | null = null,
    @Arg('skip', () => Int, { nullable: true }) skip: number = 0,
    @Arg('take', () => Int, { nullable: true }) take: number = 25,
    @Arg('order', () => [TalentSearchOrderInput], { nullable: true }) order: Array<TalentSearchOrderInput> = [],
    @Info() info,
    @Ctx() ctx: IRequestContext,
  ) {
    const defaultFindOptions = getFindOptions(Talent, info, { transformQueryPath: x => x.replace(/^items./, '') });

    const [items, total] = addEagerFlags(await ctx.em.findAndCount(Talent, cleanDeep({
      ...defaultFindOptions,
      skip,
      take,
      where: resolveGetters(search),
      order: Object.assign({}, ...order),
    })));

    return {
      items,
      total,
      hasMore: skip + take < total,
    };
  }

  @Query(() => [Talent])
  public async talents(@Info() info, @Ctx() ctx: IRequestContext) {
    return addEagerFlags(await ctx.em.find(Talent, getFindOptions(Talent, info)));
  }

  @Mutation(() => Talent)
  public async createTalent(@Arg('input') input: TalentCreateInput, @Ctx() ctx: IRequestContext): Promise<Talent> {
    const model = new Talent();
    await model.update(input, ctx);

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Talent)
  public async updateTalent(@Arg('input') input: TalentEditInput, @Ctx() ctx: IRequestContext) {
    const model = await ctx.em.findOneOrFail(Talent, input.id);
    await model.update(input, ctx);

    // <keep-update-code>
    // </keep-update-code>

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Boolean)
  public async deleteTalents(@Arg('ids', () => [ID]) ids: Array<EntityId>, @Ctx() ctx: IRequestContext): Promise<boolean> {
    const entities = await ctx.em.findByIds(Talent, ids);
    await auth.assertCanDelete(entities, ctx);
    await ctx.em.remove(entities);

    return true;
  }

  // <keep-methods>
  // </keep-methods>
}
