/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
// tslint:disable max-line-length
import * as cleanDeep from 'clean-deep';
import { Arg, Args, Ctx, FieldResolver, ID, Info, Int, Mutation, Query, Resolver, Root } from 'type-graphql';

import * as auth from '../../../utils/auth/auth-checkers';
import { getFindOptions } from '../../../utils/get-find-options';
import { resolveGetters } from '../../../utils/resolve-getters';
import { EntityId, EntityIdScalar } from '../../EntityId';
import { IRequestContext } from '../../IRequestContext';
import { PaginatedResponse } from '../../PaginationResponse';
import { PostCreateInput } from '../inputs/PostCreateInput';
import { PostEditInput } from '../inputs/PostEditInput';
import { PostSearchInput } from '../inputs/PostSearchInput';
import { PostSearchOrderInput } from '../inputs/PostSearchOrderInput';
import { Post } from '../models/Post';

// <keep-imports>
// </keep-imports>

const PaginatedPostResponse = PaginatedResponse(Post);

@Resolver(Post)
export class PostCrudResolver {
  @Query(() => Post)
  public async post(@Arg('id', () => EntityIdScalar) id: number, @Info() info, @Ctx() ctx: IRequestContext) {
    return ctx.em.findOneOrFail(Post, id, getFindOptions(Post, info));
  }

  @Query(() => PaginatedPostResponse)
  public async searchPosts(
    @Arg('search', () => PostSearchInput, { nullable: true }) search: PostSearchInput | null = null,
    @Arg('skip', () => Int, { nullable: true }) skip: number = 0,
    @Arg('take', () => Int, { nullable: true }) take: number = 25,
    @Arg('order', () => [PostSearchOrderInput], { nullable: true }) order: Array<PostSearchOrderInput> = [],
    @Info() info,
    @Ctx() ctx: IRequestContext,
  ) {
    const defaultFindOptions = getFindOptions(Post, info, { transformQueryPath: x => x.replace(/^items./, '') });

    const [items, total] = await ctx.em.findAndCount(Post, cleanDeep({
      ...defaultFindOptions,
      skip,
      take,
      where: resolveGetters(search),
      order: Object.assign({}, ...order),
    }));

    return {
      items,
      total,
      hasMore: skip + take < total,
    };
  }

  @Query(() => [Post])
  public async posts(@Info() info, @Ctx() ctx: IRequestContext) {
    return ctx.em.find(Post, getFindOptions(Post, info));
  }

  @Mutation(() => Post)
  public async createPost(@Arg('input') input: PostCreateInput, @Ctx() ctx: IRequestContext): Promise<Post> {
    const model = new Post();
    await model.update(input, ctx);

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Post)
  public async updatePost(@Arg('input') input: PostEditInput, @Ctx() ctx: IRequestContext) {
    const model = await ctx.em.findOneOrFail(Post, input.id);
    await model.update(input, ctx);

    // <keep-update-code>
    // </keep-update-code>

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Boolean)
  public async deletePosts(@Arg('ids', () => [ID]) ids: Array<EntityId>, @Ctx() ctx: IRequestContext): Promise<boolean> {
    const entities = await ctx.em.findByIds(Post, ids);
    await auth.assertCanDelete(entities, ctx);
    await ctx.em.remove(entities);

    return true;
  }

  // <keep-methods>
  // </keep-methods>
}
